database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:/HibernateExampleServiceDB;DB_CLOSE_DELAY=-1;
  user: sa
  password: sa
  validationQuery: "/* HibernateExampleService Health Check */ SELECT 1"
logging:
  level: INFO
  loggers:
    org.hibernate:
      level: WARN